<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EnfantSeeder extends Seeder
{
    public function run()
    {
        DB::table('enfants')->insert([
            [
                'prive_id' => 3,
                'nom' => 'Dupont',
                'prenom' => 'Alice',
                'dateNaissance' => '2010-05-15',
                'adresse' => '123 Rue de Paris',
                'codePostal' => '75001',
                'localite' => 'Paris',
                'noAVS' => '123456789012',
                'noContribuable' => '987654321',
                'revenuBrut' => 5000.00,
                'fortuneNet' => 10000.00,
                'avantAgeScolaire' => false,
                'handicap' => false,
                'domicileAvecParents' => false,
                'parentsViventEnsemble' => true,
                'gardeAlternee' => false,
                'priseEnChargeFraisEgale' => false,
                'revenuNetSuperieurAAutreParent' => false,
                'fraisGarde' => 200.00,
                'primeAssuranceMaladie' => 150.00,
                'subsideAssuranceMaladie' => 50.00,
                'fraisMedicaux' => 100.00,
                'primeAssuranceAccident' => 75.00,
                'allocationsFamilialesSuisse' => 300.00,
                'montantInclusDansSalaireBrut' => false,
                'allocationsFamilialesEtranger' => 200.00,
                'fo_scolaire' => true,
                'fo_scolaireStope' => false,
                'fo_certificatSalaire' => false,
                'fo_attestationFortune' => false,                  
                'fo_preuveVersementPensionAlim' => false,
                'fo_preuveEncaissementPensionAlim' => false,
                'fo_avanceScarpa' => false,
                'fo_fraisGardeEffectifs' => false,
                'fo_attestationAMPrimesAnnuel' => false,
                'fo_attestationAMFraisMedicaux' => false,
                'fo_attestationPaiementAssuranceAccident' => false,
            ],
            [
                'prive_id' => 2,
                'nom' => 'Smith',
                'prenom' => 'Bob',
                'dateNaissance' => '2012-10-20',
                'adresse' => '456 Avenue de Bruxelles',
                'codePostal' => '1000',
                'localite' => 'Bruxelles',
                'noAVS' => '987654321098',
                'noContribuable' => '123456789',
                'revenuBrut' => 3000.00,
                'fortuneNet' => 5000.00,
                'avantAgeScolaire' => true,
                'handicap' => false,
                'domicileAvecParents' => true,
                'parentsViventEnsemble' => false,
                'gardeAlternee' => true,
                'priseEnChargeFraisEgale' => true,
                'revenuNetSuperieurAAutreParent' => true,
                'fraisGarde' => 350.00,
                'primeAssuranceMaladie' => 180.00,
                'subsideAssuranceMaladie' => 60.00,
                'fraisMedicaux' => 120.00,
                'primeAssuranceAccident' => 80.00,
                'allocationsFamilialesSuisse' => 250.00,
                'montantInclusDansSalaireBrut' => true,
                'allocationsFamilialesEtranger' => 0.00,
                'fo_scolaire' => false,
                'fo_scolaireStope' => false,
                'fo_certificatSalaire' => true,
                'fo_attestationFortune' => true,                  
                'fo_preuveVersementPensionAlim' => true,
                'fo_preuveEncaissementPensionAlim' => false,
                'fo_avanceScarpa' => false,
                'fo_fraisGardeEffectifs' => true,
                'fo_attestationAMPrimesAnnuel' => true,
                'fo_attestationAMFraisMedicaux' => true,
                'fo_attestationPaiementAssuranceAccident' => false,
            ],
        ]);
    }
}
