<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    public function run()
    {
        DB::table('User')->insert([
            [
                'nom' => 'Jean Dupont',
                'email' => 'admin@example.com',
                'motDePasse' => Hash::make('password'),
                'localite' => 'Genève',
                'adresse' => 'Rue du Rhône 1',
                'codePostal' => '1204',
                'numeroTelephone' => '0221234567',
                'role' => 'admin',
                'statut' => 'approved',
                'dateCreation' => now(),
            ],
            [
                'nom' => 'Claire Morel',
                'email' => 'admin2@example.com',
                'motDePasse' => Hash::make('password'),
                'localite' => 'Carouge',
                'adresse' => 'Avenue de la Praille 20',
                'codePostal' => '1227',
                'numeroTelephone' => '0227654321',
                'role' => 'admin',
                'statut' => 'approved',
                'dateCreation' => now(),
            ],
            [
                'nom' => 'Société Alpha SA',
                'email' => 'entreprise@example.com',
                'motDePasse' => Hash::make('password'),
                'localite' => 'Lancy',
                'adresse' => 'Chemin des Sports 12',
                'codePostal' => '1212',
                'numeroTelephone' => '0223344556',
                'role' => 'entreprise',
                'statut' => 'approved',
                'dateCreation' => now(),
            ],
            [
                'nom' => 'Isabelle Martin',
                'email' => 'prive@example.com',
                'motDePasse' => Hash::make('password'),
                'localite' => 'Vernier',
                'adresse' => 'Rue du Village 45',
                'codePostal' => '1214',
                'numeroTelephone' => '0229988776',
                'role' => 'prive',
                'statut' => 'pending',
                'dateCreation' => now(),
            ],
            [
                'nom' => 'Marc Keller',
                'email' => 'prive2@example.com',
                'motDePasse' => Hash::make('password'),
                'localite' => 'Meyrin',
                'adresse' => 'Route de Meyrin 210',
                'codePostal' => '1217',
                'numeroTelephone' => '0225566778',
                'role' => 'prive',
                'statut' => 'approved',
                'dateCreation' => now(),
            ],
            [
                'nom' => 'Elena Rossi',
                'email' => 'prive3@example.com',
                'motDePasse' => Hash::make('password'),
                'localite' => 'Onex',
                'adresse' => 'Rue des Bossons 10',
                'codePostal' => '1213',
                'numeroTelephone' => '0221122334',
                'role' => 'prive',
                'statut' => 'approved',
                'dateCreation' => now(),
            ],
            [
                'nom' => 'Julien Favre',
                'email' => 'prive4@example.com',
                'motDePasse' => Hash::make('password'),
                'localite' => 'Thônex',
                'adresse' => 'Route de Jussy 36',
                'codePostal' => '1226',
                'numeroTelephone' => '0226677889',
                'role' => 'prive',
                'statut' => 'approved',
                'dateCreation' => now(),
            ],
            [
                'nom' => 'Société Bonjour SA',
                'email' => 'entreprise2@example.com',
                'motDePasse' => Hash::make('password'),
                'localite' => 'Carouge',
                'adresse' => 'Chemin des Ports 12',
                'codePostal' => '1227',
                'numeroTelephone' => '0222222222',
                'role' => 'entreprise',
                'statut' => 'approved',
                'dateCreation' => now(),
            ],
            [
                'nom' => 'Société Hello SA',
                'email' => 'entreprise3@example.com',
                'motDePasse' => Hash::make('password'),
                'localite' => 'Lyon',
                'adresse' => 'Rue de la République 50',
                'codePostal' => '69001',
                'numeroTelephone' => '0472123456',
                'role' => 'entreprise',
                'statut' => 'pending',
                'dateCreation' => now(),
            ],
            [
                'nom' => 'Boran UZUN',
                'email' => 'boran.uzun@etu.hesge.ch',
                'motDePasse' => Hash::make('password'),
                'localite' => 'Carouge',
                'adresse' => 'Rue de la Mairie 1',
                'codePostal' => '1227',
                'numeroTelephone' => '0791234567',
                'role' => 'prive',
                'statut' => 'pending',
                'dateCreation' => now(),
            ],
        ]);
    }
}
